### ISSUE TITLE
Handling when jobs write into the same output_dir

### ISSUE THREAD

**Issue by Oufattole** [mmcdermott/hydra_profiler#4]
When I run a script with `--multirun` and a single job with `joblib`, I observe that each run writes logs to the same hydra.runtime.output_dir path. Would we want to support this workflow here by prepending some count or date to the output file path of these logs, or are users expected to update the output_dir path themselves.

Looks like in meds-tab we currently write job logs for `hydra.job.num` 1 to the same directory (i.e. every trial assigned to job/worker 1 will output logs in the same directory causing this issue): https://github.com/mmcdermott/MEDS_Tabular_AutoML/pull/127

**Comment by Oufattole** [comment]
Seems to be a meds-tab issue that is resolved by adding the hydra.job.num to the job names:
```yaml
hydra:
  verbose: False
  job:
    name: MEDS_TAB__LOG_NAME_${log_name}__WORKER${worker}__HYDRA_JOB_NUM_${hydra.job.num}__DATE_${now:%Y-%m-%d}_${now:%H-%M-%S}
    num: 0
  sweep:
    dir: ${log_dir}
  run:
    dir: ${log_dir}
```
